package:
  name: doicomp	
  version: 1

source:
  git_rev: 
  git_url: https://github.com/drdaley/doicomp.git

requirements:
  build:
    - python
    - setuptools

  run:
    - python

test:
  imports: citation_diffs.py
    -

about:
  home:
  license:
  license_file: